### ISSUE TITLE
I got a ReadTimeout when an event stream send blank lines

### ISSUE THREAD

**Issue by lucafaggianelli** [florimondmanca/httpx-sse#14]
Hey nice library!

I'm trying to read an event stream that sends some empty lines and I receive an `httpx.ReadTimeout`:

```
Traceback (most recent call last):
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\engie_dash_hub\azure_log_stream.py", line 28, in <module>
    asyncio.run(stream_app_service_logs())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\engie_dash_hub\azure_log_stream.py", line 19, in stream_app_service_logs
    async for event in event_source.aiter_sse():
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx_sse\_api.py", line 39, in aiter_sse
    async for line in self._response.aiter_lines():
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_models.py", line 961, in aiter_lines
    async for text in self.aiter_text():
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_models.py", line 948, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_models.py", line 927, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_models.py", line 985, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_transports\default.py", line 238, in __aiter__
    with map_httpcore_exceptions():
  File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\LQ6211\dev\experiments\engie_dash_hub\backend\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

Though the event stream is sending data, indeed I tapped into your `aiter_sse` function and added a print and got this:
```
got line 2023-05-17T10:20:34  Welcome, you are now connected to log-streaming service.
got line 
got line Starting Log Tail -n 10 of existing logs ----
got line
got line Ending Log Tail of existing logs ---
got line
got line Starting Live Log Stream ---
```

Moreover, aside from the ReadTimeout error, I don't receive any event, even those with some content, that is, using this code I don't see anything printed in the console:

```py
async with httpx.AsyncClient(verify=False) as client:
        async with aconnect_sse(client, "GET", url) as event_source:
            async for event in event_source.aiter_sse():
                print(event)
```

The modified `aiter_sse` function for ref
```py
    async def aiter_sse(self) -> AsyncIterator[ServerSentEvent]:
        self._check_content_type()
        decoder = SSEDecoder()
        async for line in self._response.aiter_lines():
            line = line.rstrip("\n")
            print("got line", line)
            sse = decoder.decode(line)
            if sse is not None:
                yield sse
```

thanks a lot!

**Comment by florimondmanca** [comment]
Hi there,

Could this be because the service _does not_ send SSE lines for a while, and then HTTPX times out because of that?

I assume some services send either blank or comment lines to avoid this issue.

You might also just want to disable read timeouts on your HTTPX call?

If the server _does_ send events, then that would be another issue, but ReadTimeout comes from HTTPX not getting inbound data on the network socket, so…

**Comment by florimondmanca** [comment]
The fact that you’re able to use aconnect_sse means that the Asure endpoint does send the correct SSE accept header and such.

But it looks to not be complying with the formatting of SSE messages. Since there’s no `\r\n` to separate the messages out, the decoder is buffering up indefinitely.

If you don’t care about the SSE request / response formalities, you could just `.astream()` and call `.aiter_lines()`, that is not using this package at all.

I’ll close this as I don’t think there’s anything actionable here, but happy to discuss further.

**Comment by lucafaggianelli** [comment]
A wow that's great, thank you so much! indeed I was able to recreate the same functionality with plain `httpx`:

```py
async def stream_app_service_logs():
    async with httpx.AsyncClient(verify=False, timeout=httpx.Timeout(60)) as client:
        async with client.stream("GET", url) as stream:
            async for log_line in stream.aiter_lines():
                yield log_line.rstrip("\n")
```

though I'm still using `EventSourceResponse` to create a SSE on my side:

```py
@api.get("/projects/{project_id}/logs")
async def stream_logs():
    generator = stream_app_service_logs()
    return EventSourceResponse(generator)
```
